import type { NextPage } from 'next'
import Head from 'next/head'
import { Listing } from "../features/listing/components/Listing";

const Index: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Doll Directory</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container mx-auto">
          <h1 className="text-3xl font-bold mt-8 mb-16">Doll Directory</h1>
          <div className="grid md:grid-cols-4 md:gap-4 md:gap-y-16 grid-cols:1 gap-8">
            {[...Array(7)].map(() =>
              // eslint-disable-next-line react/jsx-key
              <Listing
                price={30000}
                title="Pink Karambit"
                sellerName="Niko Rain"
                sellerPhoneNumber="(123) 456-7890"
              />
            )}
          </div>
        </div>
      </main>
    </div>
  )
}

export default Index
