import type { NextPage } from 'next'
import Head from 'next/head'
import { Listings } from "../features/listing/components/Listings";
import {Navbar} from "../components/Navbar";

const Index: NextPage = () => (
  <div>
    <Head>
      <title>Doll Directory</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700&display=swap" rel="stylesheet" />
    </Head>
    <main>
      <Navbar />
      <div className="container mx-auto mt-12">
        <Listings />
      </div>
    </main>
  </div>
)

export default Index
